(gitlab-ci): Added run test server (eterbug #13053)

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -67,13 +67,13 @@ test build:
     - mkdir -p $RPMDIR/sources
     #- eterremove remove --days $DEV_EXPIRE_IN --notest dirs ${DEV_RPMDIR} || echo "ignore remove error.."
     - /usr/bin/rpmlog -q -r -l
-    #- korinf -f rxclient.spec x86_64/ALTLinux/p8 ${RPMDIR}
+    - korinf -f rxclient.spec x86_64/ALTLinux/p8 ${RPMDIR}
     - korinf -f rxclient.spec x86_64/ALTLinux/Sisyphus ${RPMDIR}
-    #- korinf -f rxclient.spec x86_64/ALTLinux/p7 ${RPMDIR}
+    - korinf -f rxclient.spec x86_64/ALTLinux/p7 ${RPMDIR}
     # 32 bit
-    #- korinf -f rxclient.spec ALTLinux/p8 ${RPMDIR}
-    #- korinf -f rxclient.spec ALTLinux/Sisyphus ${RPMDIR}
-    #- korinf -f rxclient.spec ALTLinux/p7 ${RPMDIR}
+    - korinf -f rxclient.spec ALTLinux/p8 ${RPMDIR}
+    - korinf -f rxclient.spec ALTLinux/Sisyphus ${RPMDIR}
+    - korinf -f rxclient.spec ALTLinux/p7 ${RPMDIR}
   only:
     - /^ci-.*/
     - /^docker-ci-.*/
@@ -89,24 +89,25 @@ Testing:
     - export DAAS_OUTDIR="$CI_PROJECT_DIR/daas-rxclient"
     - export DAAS_IMAGE_POSTFIX="-$CI_COMMIT_REF_NAME-build$BUILD_ID"
     - export "SERVICE_NAME=rxclient-$BUILD_ID"
+    - export "SERVER_NAME=rx-etersoft-$BUILD_ID"
     - subst "s|{{BUILD_ID}}|$BUILD_ID|g" $CI_PROJECT_DIR/.daas/addons/rx-test.list
     - daas gen 
     - |
       echo "SERVICE_NAME=$SERVICE_NAME" > "$DAAS_OUTDIR/rxclient-$BUILD_ID/.env"
       echo "BUILD_ID=$BUILD_ID" >> "$DAAS_OUTDIR/rxclient-$BUILD_ID/.env"
+    - mkdir -p $DAAS_OUTDIR/rxclient-config
   script:
-    - cd $DAAS_OUTDIR/rxclient-$BUILD_ID/
+    - cd $DAAS_OUTDIR
     - docker-compose build --force-rm
-    #- $HOME/bin/start-rx-etersoft-test-server.sh
     - docker-compose up -d
-    - export RX_SERVER_IP=$(curl -s http://localhost:8500/v1/catalog/service/$SERVICE_NAME | jq '.[].ServiceAddress' | sed 's|"||g')
-    #- cat $CI_PROJECT_DIR/.daas/templates/rx-rxclient.nxs.tpl | sed "s|RX_SERVER_IP|${RX_SERVER_IP}|g" > $HOME/$RXCLIENT_CONFDIR/rx-$BUILD_ID.nxs
-    #- chmod a+rw $HOME/$RXCLIENT_CONFDIR/rxrxclient-$BUILD_ID.nxs || echo "ignore chmod error.."
-    # удаляем старые файлы конфигурации
-    #- find $HOME/$RXCLIENT_CONFDIR/ -mindepth 1 -mtime +$DEV_EXPIRE_IN -print -delete || echo "ignore delete old configs error"
+    - export RX_CLIENT_IP=$(curl -s http://localhost:8500/v1/catalog/service/$SERVICE_NAME | jq '.[].ServiceAddress' | sed 's|"||g')
+    - export RX_SERVER_IP=$(curl -s http://localhost:8500/v1/catalog/service/$SERVER_NAME | jq '.[].ServiceAddress' | sed 's|"||g')
+    - cat $CI_PROJECT_DIR/.daas/templates/rx-server.nxs.tpl | sed "s|RX_SERVER_IP|${RX_SERVER_IP}|g" > $DAAS_OUTDIR/rxclient-config/rx-server.nxs
+    - chmod a+rw $DAAS_OUTDIR/rxclient-config/rx-server.nxs || echo "ignore chmod error.."
     - | 
-      echo "           RXCLIENT IP: $RX_SERVER_IP"
+      echo "           RXCLIENT IP: $RX_CLIENT_IP"
       echo "REMOTE CONNECT COMMAND: ssh -p $CI_BUILD_ID guest@$(hostname -s)"
+      echo "             RX-SERVER: $RX_SERVER_IP"
 
   only:
     - /^docker-ci-.*/
@@ -122,9 +123,7 @@ Cleanup:
     - export "SERVICE_NAME=rxclient-$BUILD_ID"
   script:
     - echo "Stop & remove containers"
-    - daas gen 
-    - cd $DAAS_OUTDIR/rxclient-$BUILD_ID/
-    - docker-compose down
+    - daas down
     #- docker image prune -f
     #- docker container prune -f
     #- docker volume prune -f
